# Generated by Django 2.2.25 on 2021-12-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ders_adi', models.CharField(max_length=150, verbose_name='Ders')),
                ('proje_ozeti', models.TextField(max_length=4000, verbose_name='Ozet')),
                ('proje_teslim_donemi', models.CharField(max_length=150, verbose_name='Teslim Donemi')),
                ('proje_basligi', models.CharField(max_length=500, verbose_name='Proje Basligi')),
                ('anahtar_kelimeler', models.CharField(max_length=700, verbose_name='Anahtar Kelimeler')),
                ('danisman_bilgileri', models.CharField(max_length=400, verbose_name='Danisman Bilgileri')),
                ('juri_bilgileri', models.CharField(max_length=400, verbose_name='Juri Bilgileri')),
                ('pdf', models.FileField(upload_to='downloads')),
            ],
        ),
    ]
