# Generated by Django 2.2.25 on 2021-12-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='ogr_adi',
            field=models.CharField(max_length=150, null=True, verbose_name='Ogrenci Adi'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='ogr_no',
            field=models.CharField(max_length=150, null=True, verbose_name='Ogrenci No'),
        ),
    ]
