# Generated by Django 2.2.25 on 2021-12-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0002_auto_20211220_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='ogr_tur',
            field=models.CharField(max_length=150, null=True, verbose_name='Ogrenci No'),
        ),
    ]
