# Generated by Django 2.2.25 on 2021-12-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0003_pdf_ogr_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='ogr_tur',
            field=models.CharField(max_length=150, null=True, verbose_name='Ogretim Turu'),
        ),
    ]
