# Generated by Django 2.2.25 on 2021-12-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0004_auto_20211220_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='downloads', verbose_name='PDF dosyasi'),
        ),
    ]
